version: "3.7"

services:
    svsdbot:
        build: .
        cap_add:
         - ALL
        restart: always
        container_name: "svsdbot"
        hostname: svsdbot
        volumes:
         - .:/var/svsdbot
        dns:
         - 8.8.8.8
         - 8.8.4.4